sformat = """
$time\
$username\
$hostname\
$localip\
$shlvl\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$deno\
$golang\
$guix_shell\
$helm\
$java\
$kotlin\
$nodejs\
$opa\
$python\
$scala\
$memory_usage\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$status\
$os\
$container\
$shell\
$character"""